[SERV-106] Only Add Metadata for Audio/Video Media
UCLALibrary/services-metagetter pull request #10
Opened 2021-04-19 22:32 UTC by DRickard

Changes:
* Added fields to CsvHeaders
* Updated MetadataSetter to check media mime type before adding metadata to CSV
* Added unit test to MetadataSetterTest

2021-04-19 22:50 UTC, markmatney commented on src/main/java/edu/ucla/library/services/metadata/CsvHeaders.java
> +                case "media.width":
I noticed these values are already defined in MetadataSetter as `HEADER_WIDTH`, `HEADER_HEIGHT`, etc. Could we define them in a single place?

2021-04-20 01:13 UTC, ksclarke requested changes
I'd agree with the one request Mark made. I don't have any other concerns... looks good.

2021-04-20 19:49 UTC, ksclarke approved these changes

2021-04-20 20:03 UTC, markmatney approved these changes

2021-04-20 20:08 UTC, merged