Update README.md
UCLALibrary/services-metagetter pull request #11
Opened 2021-04-27 20:54 UTC by DRickard

Filling in details on how to build/run application

2021-04-27 22:43 UTC, ksclarke requested changes

2021-04-27 22:43 UTC, ksclarke commented on README.md
> +Java app that parses DLCS CSV files, extracts paths for A/V media files, uses ffmpeg to extract metadat (height/width, duration, and MIME type), and adds the metadata to the CSV.
metadata instead of metadat

2021-04-27 23:09 UTC, DRickard commented on README.md
> +Java app that parses DLCS CSV files, extracts paths for A/V media files, uses ffmpeg to extract metadat (height/width, duration, and MIME type), and adds the metadata to the CSV.
D'oh!

2021-04-28 01:52 UTC, ksclarke approved these changes

2021-04-28 16:09 UTC, markmatney approved these changes

2021-04-28 16:15 UTC, merged